//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEstudianteYMateria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public int nrc { get; set; }
        public string descripcion { get; set; }
        public string hashkey { get; set; }
    }
}
